storage:
  baseDir: "api"
  backupDirectory: "backup"
  compression: false
  fileExtensions: false
  csvDelimiter: " "

api:
  baseUrl: "https://forbes.com/forbesapi/"
  endpoints:
    list: "person/{URI}/0/position/true.json"
    profile: "person/{URI}.json"
  rateLimiting:
    batch: 25
